name: Run Python Script

on:
  schedule:
    - cron: "0 0 * * *"  # This cron expression runs at 12 AM UTC daily
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run script
      run: |
        cp config.ini.sample config.ini  # Adjust if necessary
        source .venv/bin/activate
        python c:/Proyectos/SIL-Scrapper/main.py
